apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.bundleUtilsSecrets.name }}
  labels:
    app.kubernetes.io/name: {{ include "bundleutils.name" . }}
    helm.sh/chart: {{ include "bundleutils.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $key, $val := .Values.bundleUtilsSecrets.data }}
  {{ $key }}: "{{ $val }}"
{{- end }}
